[package]
name = "pi"
version = "0.1.0"
authors = ["Aleksandrs Zaslavskis <sahsariga111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rust-ini = "0.15"
rppal = "0.11.3"