name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  cd core && cd nightly && cd 24112020 && cargo build --verbose
    - name: Run tests
      run:   cd core && cd nightly && cd 24112020 &&  cargo test --verbose
